### ISSUE TITLE
Building in release mode fails

### ISSUE THREAD

**Issue by LouisDhauwe** [lrtitze/Swift-VectorBoolean#2]
When building the project in release mode I get 2 errors:

`Undefined symbols for architecture arm64:
  "direct type metadata for ext.Swift_VectorBoolean.__ObjC.CGPath.Element", referenced from:
      l_get_field_types_LRTBezierPathWrapper in LRTBezierPathWrapper.o
      generic specialization <Swift._ArrayBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element> with Swift._ArrayBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element> : Swift._ArrayBufferType in Swift, ext.Swift_VectorBoolean.__ObjC.CGPath.Element, Swift.IndexingGenerator<Swift._ArrayBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element>> with Swift.IndexingGenerator<Swift._ArrayBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element>> : Swift.GeneratorType in Swift, ext.Swift_VectorBoolean.__ObjC.CGPath.Element, Swift.Int with Swift.Int : Swift.ForwardIndexType in Swift, Swift.Int with Swift.Int : Swift._SignedIntegerType in Swift, Swift.Int with Swift.Int : Swift._BuiltinIntegerLiteralConvertible in Swift, Swift.Int, Swift._SliceBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element> with Swift._SliceBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element> : Swift.Indexable in Swift and Swift._SliceBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element> : Swift.SequenceType in Swift, Swift.IndexingGenerator<Swift._SliceBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element>> with Swift.IndexingGenerator<Swift._SliceBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element>> : Swift.GeneratorType in Swift, ext.Swift_VectorBoolean.__ObjC.CGPath.Element, Swift.Int with Swift.Int : Swift.ForwardIndexType in Swift, Swift.Int with Swift.Int : Swift._SignedIntegerType in Swift, Swift.Int with Swift.Int : Swift._BuiltinIntegerLiteralConvertible in Swift, Swift.Int, Swift._SliceBuffer<ext.Swift_VectorBoolean.__ObjC.CGPath.Element>, ext.Swift_VectorBoolean.__ObjC.CGPath.Element, ext.Swift_VectorBoolean.__ObjC.CGPath.Element> of Swift._forceCreateUniqueMutableBuffer <A where A: Swift._ArrayBufferType> (inout A, newCount : Swift.Int, countForCapacity : Swift.Int) -> Swift._ContiguousArrayBuffer<A.Element> in LRTBezierPathWrapper.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

This seems to be related to the Swift optimization level, when setting it to None[-Onone], the build succeeds.

**Comment by lrtitze** [comment]
I think I have this one figured out (finally!)

I declared the Element enum inside our extension to CGPath so it appears to be invisible to the optimizer.

I'm moving it outside the extension as a public enum (and renaming it) to get rid of the problem.

I'll commit the fix and close this issue shortly.

**Comment by LouisDhauwe** [comment]
Awesome, optimized Swift code (especially with Whole Module Optimizations) should give a nice performance boost.
