### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by an0** [lrtitze/Swift-VectorBoolean#6]
Anyone working it? If no I may have to.

**Comment by lrtitze** [comment]
I haven't had time to begin this yet. It may be quite a chore. I'd love to fix the function names to remove some of the awkwardness inherited from the original Objective-C.

**Comment by an0** [comment]
@lrtitze I see. If any of us starts please let others know so that we won't do duplicate work.

**Comment by LouisDhauwe** [comment]
Please see pull request #7

**Comment by lrtitze** [comment]
Great job Louis.

**Comment by LouisDhauwe** [comment]
You're welcome, can this issue be closed?
